// Question types
export const FETCH_MBTI = 'FETCH_MBTI'
export const FETCH_FAKBOI = 'FETCH_FAKBOI'
export const FETCH_NEGARAMANA = 'FETCH_NEGARAMANA'

// Test types
export const ADD_ANSWER = 'ADD_ANSWER'
export const ADD_ANSWERED = 'ADD_ANSWERED'
export const ADD_PILGAN_ANSWER = 'ADD_PILGAN_ANSWER'
export const ADD_PILGAN_ANSWERED = 'ADD_PILGAN_ANSWERED'
export const TEST_START = 'TEST_START'
export const TEST_END = 'TEST_END'

// Sort & Filter types
export const SORT_BARU = 'SORT_BARU'
export const SORT_POPULER = 'SORT_POPULER'
export const FILTER_FUN = 'FILTER_FUN'
export const FILTER_PSIKOLOGI = 'FILTER_PSIKOLGI'
export const FILTER_KARIR_EDUKASI = 'FILTER_KARIR_EDUKASI'
export const NO_FILTER = 'NO_FILTER'

// Auth types
export const AUTHENTICATE_USER = 'AUTHENTICATE_USER'
export const AUTHECTICATE_FAILED = 'AUTHECTICATE_FAILED'
export const AUTHENTICATE_DESTROY = 'AUTHENTICATE_DESTROY'
export const AUTHENTICATE_LOADING = 'AUTHENTICATE_LOADING'

// Update
export const UPDATE_PROFILE = 'UPDATE_PROFILE'